POST https://mighty-badlands-64956.herokuapp.com/Graphql

Content-Type: application/json
X-REQUEST-TYPE: GraphQL


mutation login($email: String!, $password: String!, $lenguage: String!) {
  login(email: $email, password: $password, lenguage: $lenguage) {
    email
    id
    token
    userName
  }
}

{
  "email" : "user5@gmail.com",
  "password" : "12345678",
  "lenguage" : "español"
}